export const prompts = [
  "Scrie un cântec despre o culoare și emoțiile pe care le trezește.",
  "Imaginează-ți lumea prin ochii unui animal de companie.",
  "Începe un cântec cu versul: „Liniștea a țipat mai tare decât orice mulțime.”",
  "Gândește-te la o persoană pe care o admiri și scrie un cântec despre impactul ei.",
  "Scrie un refren care schimbă complet atmosfera piesei.",
  "Știați că? Sincoparea este o rupere intenționată a ritmului obișnuit într-o măsură muzicală.",
  "Creează un cântec inspirat de sentimentul de nostalgie.",
  "Scrie versuri despre un secret pe care nu l-ai spus niciodată nimănui.",
  "Știați că? Un „riff” este o succesiune repetată de note, des întâlnită în rock și jazz.",
  "Compune un cântec în jurul unei întrebări ca temă centrală.",
  "Scrie un cântec despre senzația de rătăcire.",
  "Imaginează-ți o scrisoare pe care nu o vei trimite niciodată și transform-o în versuri.",
  "Începe un cântec cu versul: „Luminile orașului pictau cerul cu dor.”",
  "Gândește-te la un eveniment istoric și scrie din perspectiva cuiva care l-a trăit.",
  "Scrie o strofă folosind doar verbe.",
  "Știați că? Armonia este combinația de note cântate simultan pentru a crea acorduri.",
  "Creează un cântec inspirat de mișcarea apei.",
  "Scrie versuri despre un moment de bucurie neașteptată.",
  "Știați că? Tempo-ul este viteza sau ritmul unei piese muzicale.",
  "Compune un cântec care spune o poveste fără să folosești cuvântul „eu”.",
  "Scrie un cântec despre trecerea timpului.",
  "Imaginează-ți o conversație cu versiunea ta mai tânără și transform-o în versuri.",
  "Începe un cântec cu versul: „Fotografia veche păstra un zâmbet uitat.”",
  "Gândește-te la un fenomen natural (ca o furtună sau un răsărit) și descrie-l prin muzică.",
  "Scrie un refren care eliberează tensiunea acumulată.",
  "Știați că? Melodia este o succesiune de note muzicale care sună plăcut împreună.",
  "Creează un cântec inspirat de sentimentul de anticipare.",
  "Scrie versuri despre un loc care nu mai există.",
  "Știați că? Ritmul este modelul de silabe accentuate și neaccentuate sau de note muzicale.",
  "Compune un cântec bazat pe un anumit tipar ritmic.",
  "Scrie un cântec despre frica de necunoscut.",
  "Imaginează-ți un mesaj lăsat pe robotul telefonic și transformă-l în versuri.",
  "Începe un cântec cu versul: „Vântul șoptea secrete printre copaci.”",
  "Gândește-te la o operă de artă (pictură, sculptură etc.) și scrie un cântec inspirat de ea.",
  "Scrie o strofă în care fiecare vers rimează cu primul.",
  "Știați că? Dinamica în muzică se referă la intensitatea sunetelor - cât de tare sau încet se cântă.",
  "Creează un cântec inspirat de sentimentul că cineva te vede cu adevărat.",
  "Scrie versuri despre o promisiune încălcată.",
  "Compune un cântec care folosește o metaforă pentru a reprezenta o relație.",
  "Scrie un cântec despre senzația de libertate.",
  "Imaginează-ți un titlu de ziar din viitor și creează un cântec inspirat de povestea din spatele lui.",
  "Gândește-te la un concept științific și explorează-l emoțional într-un cântec.",
  "Scrie un refren care sună ca o mantră sau o afirmație pozitivă.",
  "Știați că? Un „crescendo” indică o creștere treptată a volumului în muzică.",
  "Creează un cântec inspirat de sentimentul de uimire.",
  "Scrie versuri despre un moment de revelație profundă.",
  "Știați că? Un sunet „staccato” este cântat scurt și tăios.",
  "Compune un cântec care alternează secțiuni muzicale contrastante pentru a exprima emoții diferite.",
];
