export const prompts = [
  "Write a song about a color and the emotions it evokes.",
  "Imagine the world from the perspective of a pet.",
  "Start a song with the line: 'The silence screamed louder than any crowd.'",
  "Think of a person you admire and write a song about their impact.",
  "Write a bridge that shifts the entire mood of the song.",
  "Musical fact: Syncopation is the deliberate upsetting of the normal pulse of a meter.",
  "Create a song inspired by the feeling of nostalgia.",
  "Write lyrics about a secret you've never told anyone.",
  "Musical fact: A 'riff' is a repeated series of musical notes, often used in rock and jazz.",
  "Compose a song with a question as its central theme.",
  "Write a song about the feeling of being lost.",
  "Imagine a letter you'll never send and turn its contents into lyrics.",
  "Start a song with the line: 'The city lights painted the sky with longing.'",
  "Think of a historical event and write a song from the perspective of someone who lived through it.",
  "Write a verse using only verbs.",
  "Musical fact: Harmony is the combination of simultaneously sounded musical notes to produce chords and chord progressions.",
  "Create a song inspired by the movement of water.",
  "Write lyrics about a moment of unexpected joy.",
  "Musical fact: Tempo is the speed or pace of a musical piece.",
  "Compose a song that tells a story without using the word 'I'.",
  "Write a song about the passage of time.",
  "Imagine a conversation with your younger self and write it as lyrics.",
  "Start a song with the line: 'The old photograph held a forgotten smile.'",
  "Think of a natural phenomenon (like a storm or sunrise) and describe it musically.",
  "Write a chorus that feels like a release of tension.",
  "Musical fact: Melody is a sequence of musical notes that are musically satisfying.",
  "Create a song inspired by the feeling of anticipation.",
  "Write lyrics about a place that no longer exists.",
  "Musical fact: Rhythm is the pattern of stressed and unstressed syllables or musical notes.",
  "Compose a song with a specific rhythm pattern as its foundation.",
  "Write a song about the fear of the unknown.",
  "Imagine a message left on an answering machine and turn it into lyrics.",
  "Start a song with the line: 'The wind whispered secrets through the trees.'",
  "Think of a piece of art (painting, sculpture, etc.) and write a song it inspires.",
  "Write a verse where every line rhymes with the first line.",
  "Musical fact: Dynamics in music refer to the loudness or softness of a sound or note.",
  "Create a song inspired by the feeling of being truly seen.",
  "Write lyrics about a broken promise.",
  "Musical fact: Improvisation is the creative activity of immediate musical composition.",
  "Compose a song that uses a metaphor to represent a relationship.",
  "Write a song about the feeling of freedom.",
  "Imagine a headline from a future newspaper and write a song about the story behind it.",
  "Start a song with the line: 'The coffee was bitter, but the conversation was sweet.'",
  "Think of a scientific concept and explore its emotional resonance in a song.",
  "Write a chorus that feels like a mantra or affirmation.",
  "Musical fact: A 'crescendo' indicates a gradual increase in loudness.",
  "Create a song inspired by the feeling of wonder.",
  "Write lyrics about a moment of profound realization.",
  "Musical fact: A 'staccato' note is played with a sharp, detached attack.",
  "Compose a song that uses contrasting musical sections to represent different emotions.",
];
